version: '2'

services:
  zookeeper0.hyperfabric.xyz:
    container_name: zookeeper0.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: zookeeper0.hyperfabric.xyz

  zookeeper1.hyperfabric.xyz:
    container_name: zookeeper1.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: zookeeper1.hyperfabric.xyz

  zookeeper2.hyperfabric.xyz:
    container_name: zookeeper2.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: zookeeper2.hyperfabric.xyz

  kafka0.hyperfabric.xyz:
    container_name: kafka0.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: kafka0.hyperfabric.xyz

  kafka1.hyperfabric.xyz:
    container_name: kafka1.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: kafka1.hyperfabric.xyz

    kafka2.hyperfabric.xyz:
    container_name: kafka2.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: kafka2.hyperfabric.xyz

  kafka3.hyperfabric.xyz:
    container_name: kafka3.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: kafka3.hyperfabric.xyz
