version: '2'

services:
  ca.org2.hyperfabric.xyz:
    container_name: ca.org2.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: ca.org2.hyperfabric.xyz

  peer0.org2.hyperfabric.xyz:
    container_name: peer0.org2.hyperfabric.xyz
    extends:
      file:  base/docker-compose-base.yml
      service: peer0.org2.hyperfabric.xyz

  peer1.org2.hyperfabric.xyz:
    container_name: peer1.org2.hyperfabric.xyz
    extends:
      file:  base/docker-compose-base.yml
      service: peer1.org2.hyperfabric.xyz
