version: '2'

services:
  ca.org3.hyperfabric.xyz:
    container_name: ca.org3.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yml
      service: ca.org3.hyperfabric.xyz

  peer0.org3.hyperfabric.xyz:
    container_name: peer0.org3.hyperfabric.xyz
    extends:
      file:  base/docker-compose-base.yml
      service: peer0.org3.hyperfabric.xyz

  peer1.org3.hyperfabric.xyz:
    container_name: peer1.org3.hyperfabric.xyz
    extends:
      file:  base/docker-compose-base.yml
      service: peer1.org3.hyperfabric.xyz

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org3.hyperfabric.xyz:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.hyperfabric.xyz/peers/peer0.org3.hyperfabric.xyz/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.hyperfabric.xyz/peers/peer0.org3.hyperfabric.xyz/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.hyperfabric.xyz/peers/peer0.org3.hyperfabric.xyz/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.hyperfabric.xyz/users/Admin@org3.hyperfabric.xyz/msp
      - CHANNEL_NAME=mychannel
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./org3-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
