version: '2'

services:
  zookeeper0.hyperfabric.xyz:
    container_name: zookeeper0.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper0.hyperfabric.xyz

  zookeeper1.hyperfabric.xyz:
    container_name: zookeeper1.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper1.hyperfabric.xyz

  zookeeper2.hyperfabric.xyz:
    container_name: zookeeper2.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper2.hyperfabric.xyz

  kafka0.hyperfabric.xyz:
    container_name: kafka0.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yaml
      service: kafka0.hyperfabric.xyz

  kafka1.hyperfabric.xyz:
    container_name: kafka1.hyperfabric.xyz
    extends:
      file: base/docker-compose-base.yaml
      service: kafka1.hyperfabric.xyz
