NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org3.hyperfabric.xyz-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org3.hyperfabric.xyz-cert.pem
    OrganizationalUnitIdentifier: peer
